"""empty message

Revision ID: 39d3ddc77119
Revises: 7e71566d1adb
Create Date: 2020-08-21 21:47:40.452778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39d3ddc77119'
down_revision = '7e71566d1adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.DATE(), nullable=True))
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=16), nullable=True))
    # ### end Alembic commands ###
