"""empty message

Revision ID: 5e10464c39c7
Revises: 39d3ddc77119
Create Date: 2020-08-21 22:22:37.658076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e10464c39c7'
down_revision = '39d3ddc77119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', mysql.ENUM('男', '女'), nullable=True))
    # ### end Alembic commands ###
