"""empty message

Revision ID: 74316f00e06b
Revises: 5e10464c39c7
Create Date: 2020-08-22 14:57:10.954338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74316f00e06b'
down_revision = '5e10464c39c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blogname', sa.String(length=20), nullable=False),
    sa.Column('blogcontent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
